### ISSUE TITLE
spring boot env vars are nonstandard

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#13]
SPRING_DATA_MONGODB_USERNAME
SPRING_DATA_MONGODB_PASSWORD
SPRING_DATA_MONGODB_DATABASE
SPRING_DATA_MONGODB_HOST

**Comment by jorgemoralespou** [comment]
Changed ENV vars name as nationalparks are no longer using Spring Cloud Config, so no longer valid
