### ISSUE TITLE
Conditional content in the modules based on activation of other modules

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/openshift-workshops#25]
In addition to the dependency relationship between modules, sometimes a module is not dependent on another module but takes a different path if that module is activated. There should be a way to include content if another module is activated.

Example of that is if the configmap module is activated, the pipeline module will also use configmaps. If not activated, pipeline module would use env vars instead.

**Comment by marekjelen** [comment]
```
{% if modules.install %}
  only if module `install` is activated
{% endif %}
```

and 

```
{{ revisions.install }} 
```
prints revision for module `install`

**Comment by marekjelen** [comment]
Initial implementation cf5612c

**Comment by marekjelen** [comment]
6ed640a is better implementation taking more complex scenarios into question

**Comment by siamaksade** [comment]
Verified 👍
