### ISSUE TITLE
[roadshow] parameterize maven/nexus usage

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#27]
need to add a parameter for when doing a roadshow/workshop so that the maven mirror usage is not shown.

This is a temporary measure until we figure out how to scale nexus in a workshop environment to support 100 simultaneous builds.

**Comment by siamaksade** [comment]
Need more info

**Comment by thoraxe** [comment]
@siamaksade updated.

**Comment by thoraxe** [comment]
Only partially fixed
