### ISSUE TITLE
[roadshow] configmap: describe fabric8 configmap interrogation or use "mount"

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#30]
Per a conversation with @siamaksade we are currently using a "feature" of spring-cloud-kubernetes and not really using configmaps like they are "normally" used (eg: mounting, in pod definition, etc)

**Comment by thoraxe** [comment]
Actually, didn't we give view access to default for parksmap a long way ago in the permissions lab?

https://github.com/openshift-evangelists/openshift-workshops/blob/fy17-roadshow-work/modules/permissions.adoc

**Comment by siamaksade** [comment]
That's true. We should remove that part then and just make rbac module a
dependency.

I think it does also make sense to do the normal mount way instead of
fabric8. Will look into it.

**Comment by siamaksade** [comment]
Fixed 72a2746960b917d91da92a424700d1aa23c7304a
