### ISSUE TITLE
[roadshow] need to keep jenkins in the same project for now

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#34]
What's the reasoning behind creating the new project for Jenkins?

**Comment by siamaksade** [comment]
@jorgemoralespou and I talked about it and concluded that's how people would do in real projects. What's the downside?

**Comment by thoraxe** [comment]
the downside is having an extra project to click back and forth through.

By that notion (real projects), shouldn't "-live" be in its own project? Or rather shouldn't "-dev" be in its own project? Would the "developer" even have access to the "live" application?

It just seems like a bit of an outlier given what we're already doing. I don't care either way, just seemed odd to me.

**Comment by siamaksade** [comment]
We can create a live project as well to make it more real life

**Comment by thoraxe** [comment]
I'd kind of rather keep everything in one project, but I can see how multiple projects would be cool.

Up to you. Do you have the time to rewrite it?

**Comment by thoraxe** [comment]
Tracking https://github.com/openshift/origin-web-console/issues/917 

I believe we will have to go with one project for now.

**Comment by thoraxe** [comment]
Confirmed that we must use one project:

https://github.com/openshift/origin-web-console/issues/917#issuecomment-262349360

I will fix.
