### ISSUE TITLE
[roadshow] nationalparks dev not using SPRING_APPLICAITON_NAME

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#35]
@jorgemoralespou @siamaksade 

At no point had we added this env var to nationalparks (dev). Do we need to? It seems to work OK without it?

**Comment by siamaksade** [comment]
Nationalparks dev doesn't need it. Live needs to override Spring Boot application name which is used by fabric8 to find the ConfigMap

**Comment by thoraxe** [comment]
You're adding a configmap to nationalparks dev. Why would you not need SPRING_APPLICATION_NAME for the dev one (with a configmap) but not the prod one (with a configmap)?

**Comment by thoraxe** [comment]
Closing becuase we're removing spring-cloud-kubernetes.
