### ISSUE TITLE
[roadshow] move de-labeling dev nationalparks service higher in pipeline lab

### ISSUE THREAD

**Issue by thoraxe** [openshift-evangelists/openshift-workshops#38]

**Comment by siamaksade** [comment]
To where and why?

**Comment by thoraxe** [comment]
to right towards the beginning of the lab (at least before deploying the -live pod) because then you will end up with both -dev and -live being served by the front-end simultaneously.

You'd have two nationalparks showing in parksmap until you de-label dev.

**Comment by siamaksade** [comment]
That doesn't really matter IMHO. You have already spent the time to change that so nevermind.
