### ISSUE TITLE
Merge fy17-roadshow-work branch into master

### ISSUE THREAD

**Issue by siamaksade** [openshift-evangelists/openshift-workshops#39]

**Comment by siamaksade** [comment]
@jorgemoralespou @marekjelen is there any reason not to?

**Comment by jorgemoralespou** [comment]
Not that I can think of. In any casem any other workshop we've done, like those for the all-in-one, will not work since all the labs, etc has been created new. Let's merge and make other labs WIP.

**Comment by siamaksade** [comment]
Merged
