### ISSUE TITLE
[roadshow] Exploring logging capabilities

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift-evangelists/openshift-workshops#53]
Remove or paraphrase this paragraph

"If you have an application that does not log to STDOUT, either because it already sends log information to some "external" system or because it writes various log information to various files, fear not. These options are still workable, although outside the scope of this workshop."

 Many applications write data to files (not STDOUT) and, we keep getting a question on whether our logging solution can read those custom log files. The above paragraph gives an impression that our solution can handle this situation. This paragraph makes audience ask that question and puts the presenter in an uncomfortable situation.

**Comment by thoraxe** [comment]
@VeerMuchandi please take a look at https://github.com/openshift-evangelists/openshift-workshops/pull/64 and approve.
