### ISSUE TITLE
[roadshow] Making Code Changes and using webhooks

### ISSUE THREAD

**Issue by VeerMuchandi** [openshift-evangelists/openshift-workshops#56]
In the section "EXERCISE: USING GITLAB WEB HOOKS"

There is a comment - 
"You actually won’t see your new name (OpenShift National Parks) in the JSON string. Why?"

Not sure why this comment exists. Once the build and deployment completes, you actually see the son string with new data as below in the browser.

http://nationalparks-explore-00.apps.devday.ocpcloud.com/ws/info/

{"id":"nationalparks","displayName":"OpenShift National Parks","center":{"latitude":"47.039304","longitude":"14.505178"},"zoom":4}

The comment above needs to be removed.

**Comment by thoraxe** [comment]
Fixed by a recent PR.
