### ISSUE TITLE
[roadshow] What should I use to provision the environment in AWS? 

### ISSUE THREAD

**Issue by alberttwong** [openshift-evangelists/openshift-workshops#57]
Should I use the OpenShift AWS reference architecture scripts? https://github.com/openshift/openshift-ansible-contrib

**Comment by thoraxe** [comment]
The "environment" is somewhat irrelevant, although the specific labs you do have environment dependencies. Currently the "roadshow" configuration expects the environment provisioned via the scripts referenced in your other issue ( #59 ).

So, the answer to your question is "it depends". Nothing is built around the AWS reference architecture. Any environment should work, although you may be missing the internal Nexus, Gitlab or lab guide itself, and would have to adjust as appropriate.
