### ISSUE TITLE
What are the instructions to run the workshop locally on my CDK?

### ISSUE THREAD

**Issue by alberttwong** [openshift-evangelists/openshift-workshops#59]
ran `oc new-app ruby~https://github.com/openshift-evangelists/openshift-workshops.git` but it seems incomplete.  What are the rest of the instructions to run the workshop locally on my CDK?

**Comment by thoraxe** [comment]
This repo is the lab guide and provides instructions for how to build the lab guide. It does not provide instructions for how to build the environment. Currently there are no instructions for how to build the environment to support this guide other than the automation provided by https://github.com/sborenst/ansible_aws_deployer

I do not believe there is a plan to include "building the environment" instructions in this repo.
